apiVersion: apps/v1
kind: Deployment
metadata:
 name: video-analyzer
spec:
 replicas: 1
 selector:
   matchLabels:
     app: video-analyzer
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: video-analyzer
   spec:
     containers:
     - image: registry.eu-west-0.prod-cloud-ocb.orange-business.com/ernest/yolov4-object-detection:latest
       imagePullPolicy: Always
       name: video-analyzer
       env:
       volumeMounts:

     imagePullSecrets:
       - name: default-secret
     volumes:
     - name: pvc-data
       persistentVolumeClaim:
         claimName: cce-sfs-import-ernest-cce-pvc