pipeline  {
    agent any

    environment {
        FE_SWR_CREDENTIALS_LOGIN    = credentials('fe-swr-credential-login')
        FE_SWR_CREDENTIALS_PASSWORD = credentials('fe-swr-credential-password')
        FE_SWR_URL = "registry.eu-west-0.prod-cloud-ocb.orange-business.com"
        FE_SWR_ORGANIZATION = "ernest"
        DOCKER_IMAGENAME = "yolov4-object-detection"
        
        
    }

    stages {
        stage ('Build') {
            steps {
                echo "Building the Docker Image"
                //def customImage = docker.build("my-nginx:${env.BUILD_ID}")        
                sh "docker build -t ${FE_SWR_URL}/${FE_SWR_ORGANIZATION}/${DOCKER_IMAGENAME}:${env.BUILD_ID} ./Build/."
            }
        }
        stage ('Register') {
            steps {
                echo "Register the Docker Image to SWR"              
                sh "docker login -u ${FE_SWR_CREDENTIALS_LOGIN} -p ${FE_SWR_CREDENTIALS_PASSWORD} ${FE_SWR_URL}"
                sh "docker push ${FE_SWR_URL}/${FE_SWR_ORGANIZATION}/${DOCKER_IMAGENAME}:${env.BUILD_ID}"
            }
        }
        stage ('Deploy to FE CCE') {
            steps {
                echo "Deploy to CCE"
                withKubeConfig(
                    caCertificate: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJTi9BVVFSeEVlQ1l3RFFZSktvWklodmNOQVFFTEJRQXdHekVaTUJjR0ExVUUKQ2hNUVEwTkZJRlJsWTJodWIyeHZaMm     xsY3pBZ0Z3MHlNREEzTWpFeE16VXlNVFphR0E4eU1EVXhNRGt4TnpFeApOVEV5TjFvd2dhZ3hlekFuQmdOVkJBb1RJREkwTW1JeU5EY3paV1JoTVRReU5qWmlOMlZtTTJZeE4ySXhZVEU0ClpUUmlNQ2NHQTFVRUNoTWdaV1JrWm     pFd1lUUXpaREEwTkRrMVlXSmlOamRpTVRRM05XWmhObVV6WkdJd0p3WUQKVlFRS0V5Qm1NbVF3WkdWbU5qZzNZbVkwWTJKaE9EZGpZbU5rTXpNek5UYzVNR0pqTlRFcE1DY0dBMVVFQXhNZwpOVE13TldKaU16aGxPVGN3TkRFek     9EbGlaR0l3TTJRM01qUXpOVFprTmpZd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDZW1SNWhGOXNGRUs1UkRkbTVlQXlUVnRhUTluZTQxWUcrNkxJU2pOejYKOTUxZWJoUjI5TG16QXhUZ1VONX     lHekUxaG9LbXYvWWZvV3NBbUtFS2pUWXdhaWh6bGRoNWEzblc5QU0xVnVPMQpwRlUrWUxzMkVhdVgxVnhNdTZXQnVkdElucGMvYTFnS3pyV0I0QXQ3bGRGRXM3blNma21zaHpjempMWVFhUDU4CjRKbUFmRUdLYmNvZXRnUmhHRU     Y2dkFGVnlUMjN0MThVYXlkM0J0SmMyUjU3M0ZGSllQNGlMS2oxSW1qNWk2U0wKWnRwZm04ZjVWQTkwQ1A3L3MyWCtIZVlOcFJuUGJkTGhCWWh2OUExUFRzdVg3UUQrRUIzZkJ5dlZTR2FoOTVwRQptamd4dzFrbHNnRmpyRG5ZV2     hSMDNmRmRaSE9PaTh0OC9rYzN6MXp5MmZSMUFnTUJBQUdqSnpBbE1BNEdBMVVkCkR3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQWhwa0RxZ09ZOVorR1     JJc1BDOXV0aThGY056TGFqdFU0bFRyK283RkdRQUFwV0ZKVThtRi9Ob3lqUWY3TAowWUYvcFdDckN4Q0dGUmhyTHFScm45S25YRE9sSms4bmJKSU9wYUtjM0diZWZURWRnNW5ka0lWcC9yalUwdzU5Cm9tbVVnaUozV29sTmRnb3     M1U2YrZ1FYWXNwei9KaVJuZWdhUkJvazIxMFJxTnNIS2IzNC8wU3FyVVppby9PQlcKQm1qSDd1R3NlVGt3Y3J3TmxpT2s1bUYyaG5iejB5d0ZZYWMzRHpNbDBPUWNIU2gvYjV1ZG9rWW5vOUVIY2l6UApoa2RzT21HNnNDaXpOTF     hCcjBmWDZudUNrVFlSQkIzdExXcFJQN09iZWt3RTM4RWorVk5WbnZYNWlvVlkxdkRGCnJudFFiWitjaWlaZ2drcTBYTFllR0NnelFRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","client-key-data":"LS0tLS1CR     UdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbnBrZVlSZmJCUkN1VVEzWnVYZ01rMWJXa1BaM3VOV0J2dWl5RW96Yyt2ZWRYbTRVCmR2UzVzd01VNEZEZWNoc3hOWWFDcHIvMkg2RnJBSmloQ28wMk1Hb     29jNVhZZVd0NTF2UUROVmJqdGFSVlBtQzcKTmhHcmw5VmNUTHVsZ2JuYlNKNlhQMnRZQ3M2MWdlQUxlNVhSUkxPNTBuNUpySWMzTTR5MkVHaitmT0NaZ0h4QgppbTNLSHJZRVlSaEJlcndCVmNrOXQ3ZGZGR3NuZHdiU1hOa2VlO     XhSU1dEK0lpeW85U0pvK1l1a2kyYmFYNXZICitWUVBkQWorLzdObC9oM21EYVVaejIzUzRRV0liL1FOVDA3TGwrMEEvaEFkM3djcjFVaG1vZmVhUkpvNE1jTloKSmJJQlk2dzUyRm9VZE4zeFhXUnpqb3ZMZlA1SE44OWM4dG4wZ     FFJREFRQUJBb0lCQUUzYkJOck5CeXVaWUxsUgpmMHhZN25OMThhY0FGdzJaWWpRQnIwa0Q5WWNOL3liWUN4dktUMDdkZUdZVnpOMWZFKzBldHd4OHQ2b1haNXZIClVXY0lvMDFwRDZxT0tOS1NQQ0dWYiszRFZjMVplcTlBZFNhN     XplNmZRc3c0WWFzcFBjaU1jZHNrS3ZoRE9UOGsKYVA2bU1URDB1WWZuanVzdkJaNDh1VE9kRnpEZG15Z1AzYW94cFZYUmZFN2FvZWJjV2xLd21nTzI1bWZ4U3lxdwppS3FiclNPSlp1SnFjbks2cUovQzhNcFNhdktXQ3B5M3JCU     0R3cjdkdGhSTDkxc2pHekxWeGtBMnNDMHhaLys3CmN1SWUvZnhzSWphc0hNRzJPOVJkbUd0RjQwbk9jNk40SzFxcDBnZ3FSUXg1VjBKaTBweGN5NkdCNXZJbXlNa1AKUlR1THdZRUNnWUVBeWZvQ0czUnpGOVRDWXgzUGxwak5aT     khsQkdtK0hpTjVZSGJUMUlIWXlvTVJDR2tvUXowdApXaEVQSyt6RE9NYVozRVBsWU9ZSm9UNU9MQmovVWhSbStsVnhQeHpscUxFYk04ZnJidUdaTnhzY0VKT2Rya2lGCkZRdUMxZTJDM1VPVnhnTm0wSGsxUDE1dWlnK0NoVWpha     Hdhbm16b0x0VVZxL1JQMytwSXh5bDBDZ1lFQXlRVFkKZ2YzTGQxQnNIZ2VNcGVmRlNieGRVOGlpa1JCVWhJckk0UTZnQkFZY05OTTVqUHprV3E0ZzY2ZEJRK2swaGNYaQpNV0RrRXhnNGdqc1F6Rlk3UjFiczltKzNMRW53VmowZ     jdidlZtVnl2RllHSlN5ay9YUU9Qek1wK3ZuaDFHK0NyCktTSDFZa3VNZEIyRkQ1SnNGNy9QUmlkQ1hlMWVUWXdFVng2YW9Qa0NnWUVBa0RUNG5ER2dtenRGTHc5eHo4eDUKbWFwaklhdCtHbmFwaXI1TXNFV2xTN0lZenpDRmxye     HZUUWN4RmVPTjMxT3ROeDhpL3ZRL20raW9WOFBoUi9GWgpOUk1jTUR1cG5iQVdBL3FSbGpGcyszTlhybDQzRHVDb1pFWTd2QkpBaFVwai9XVWdXMml2SS9lQVpRSjk1andHCkNySXRxUjdnalNSckp4YkN6eHppZitFQ2dZQU5jL     2VSYTR6TVpXTjI5d1pnckF3MkRSY3Aza21TNzhiWVAvbUYKcGxickxnV0JPNG1rZCtCSWVWTFdzcERabktmWk5BOFpRdVRBcW1STnd1b3k0cXFBOGI1V0Y4L29kT0pTd3pCNQoxcEpLK3pyMGM0RGV1Tm4ydmFCSUVsMDlIZzZvV     1BiYmY5eE9RY1FhbVVjb2JhSXlUTEh3ZmZ3aEVSdTRrT0JSCmZFalk4UUtCZ0FzYTFKcGl2VDFrYUMwbCtFK3g2VjdlVTFSaWhHM3lqd1lNVzdwNTJUaFBpb1F1TnRoYUtYcXMKZHRucm1ZM0kwNC84MUZaeWZqK0NmZ0V2Y1plR     mFZK3lpNDRvWm5CU0dZWnZJc2hXQzRUQ1ZzL2hzUzlFelcwRwpTVExUdFpiWHRTaStOUCtEZ082VXdLVUNaOFlFMFptY3ZBOUtyU2sxM0dZTEhwWTFoZHZGCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==', 
                    clusterName: '"externalCluster"', 
                    contextName: '"external',
                    credentialsId: '"user',
                    namespace: '',
                    serverUrl: 'https://90.84.243.143:5443') {

                        sh "kubectl get all"
 
                    }    
                }
        }

}
}