pipeline  {
    agent any

    environment {
        FE_SWR_CREDENTIALS_LOGIN    = credentials('fe-swr-credential-login')
        FE_SWR_CREDENTIALS_PASSWORD = credentials('fe-swr-credential-password')
        FE_SWR_URL = "registry.eu-west-0.prod-cloud-ocb.orange-business.com"
        FE_SWR_ORGANIZATION = "ernest"
        DOCKER_IMAGENAME = "yolov4-object-detection"
        
        
    }

    stages {
        stage ('Build') {
            steps {
                echo "Building the Docker Image"
                //def customImage = docker.build("my-nginx:${env.BUILD_ID}")        
                sh "docker build -t ${FE_SWR_URL}/${FE_SWR_ORGANIZATION}/${DOCKER_IMAGENAME}:${env.BUILD_ID} ./Build/."
            }
        }
        stage ('Register') {
            steps {
                echo "Register the Docker Image to SWR"              
                sh "docker login -u ${FE_SWR_CREDENTIALS_LOGIN} -p ${FE_SWR_CREDENTIALS_PASSWORD} ${FE_SWR_URL}"
                sh "docker push ${FE_SWR_URL}/${FE_SWR_ORGANIZATION}/${DOCKER_IMAGENAME}:${env.BUILD_ID}"
            }
        }
        stage ('Deploy to FE CCE') {
            steps {
                echo "Deploy to CCE"
                withKubeConfig(
                    caCertificate: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoVENDQW0yZ0F3SUJBZ0lJUTRRajE3eDdaODB3RFFZSktvWklodmNOQVFFTEJRQXdHekVaTUJjR0ExVUUKQ2hNUVEwTkZJRlJsWTJodWIyeHZaMmxsY3pBZUZ3MHlNakF5TVRjeE16UXlOVFphRncweU56QXlNVGN4TXpReQpOVFphTUlIQU1ZR1NNQ2NHQTFVRUNoTWdNalF5WWpJME56TmxaR0V4TkRJMk5tSTNaV1l6WmpFM1lqRmhNVGhsCk5HSXdKd1lEVlFRS0V5QmxaR1JtTVRCaE5ETmtNRFEwT1RWaFltSTJOMkl4TkRjMVptRTJaVE5rWWpBbkJnTlYKQkFvVElHWXlaREJrWldZMk9EZGlaalJqWW1FNE4yTmlZMlF6TXpNMU56a3dZbU0xTUJVR0ExVUVDaE1PYzNsegpkR1Z0T20xaGMzUmxjbk14S1RBbkJnTlZCQU1USURVek1EVmlZak00WlRrM01EUXhNemc1WW1SaU1ETmtOekkwCk16VTJaRFkyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFucGtlWVJmYkJSQ3UKVVEzWnVYZ01rMWJXa1BaM3VOV0J2dWl5RW96Yyt2ZWRYbTRVZHZTNXN3TVU0RkRlY2hzeE5ZYUNwci8ySDZGcgpBSmloQ28wMk1Hb29jNVhZZVd0NTF2UUROVmJqdGFSVlBtQzdOaEdybDlWY1RMdWxnYm5iU0o2WFAydFlDczYxCmdlQUxlNVhSUkxPNTBuNUpySWMzTTR5MkVHaitmT0NaZ0h4QmltM0tIcllFWVJoQmVyd0JWY2s5dDdkZkZHc24KZHdiU1hOa2VlOXhSU1dEK0lpeW85U0pvK1l1a2kyYmFYNXZIK1ZRUGRBaisvN05sL2gzbURhVVp6MjNTNFFXSQpiL1FOVDA3TGwrMEEvaEFkM3djcjFVaG1vZmVhUkpvNE1jTlpKYklCWTZ3NTJGb1VkTjN4WFdSempvdkxmUDVICk44OWM4dG4wZFFJREFRQUJveWN3SlRBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUIKQlFVSEF3SXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQTVIZXhKUDhsajk3UUFpZWlBbDcrOVVia21hbzJ6VApGUkZmcmJzNDRKc1diMi9kdVRQb1dYQzZNSFYxSnZVcUMzc0s0cTJUZGtKY1E5QTBaVnpLeUhwOFB2Rm1PTzlmCitzZHVBQlhXencxYmhkMEdlMFRMem9jUnJtbkdGTjM1N2VNaklXbmFtdGhOaGs1ZmhRMEdMVjljWldENDhuTksKK1J1YkorU1NZVERNNUNSNTNrK2FBblVpS2lWeDh5eWJqUlY5QS90d3hrZGVqOFFqK0RUK053WERYOHhSVjVtSApBaWVkVEJlL1J6eUZ3SFBjblVIQmF5VjVORytPYzN6QlUwYk5mNXM0cko1azRhUXFwOVE1Q2tGK0x6L2phLzZaCnBSRzNZRUxhcVNCaFcvMFVkL3dGM0dZcEJCcHRSeWhaU1Y2Ny94NUFQMVNZWS9rVjRsYjJKbTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K',
                    client-key-data: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbnBrZVlSZmJCUkN1VVEzWnVYZ01rMWJXa1BaM3VOV0J2dWl5RW96Yyt2ZWRYbTRVCmR2UzVzd01VNEZEZWNoc3hOWWFDcHIvMkg2RnJBSmloQ28wMk1Hb29jNVhZZVd0NTF2UUROVmJqdGFSVlBtQzcKTmhHcmw5VmNUTHVsZ2JuYlNKNlhQMnRZQ3M2MWdlQUxlNVhSUkxPNTBuNUpySWMzTTR5MkVHaitmT0NaZ0h4QgppbTNLSHJZRVlSaEJlcndCVmNrOXQ3ZGZGR3NuZHdiU1hOa2VlOXhSU1dEK0lpeW85U0pvK1l1a2kyYmFYNXZICitWUVBkQWorLzdObC9oM21EYVVaejIzUzRRV0liL1FOVDA3TGwrMEEvaEFkM3djcjFVaG1vZmVhUkpvNE1jTloKSmJJQlk2dzUyRm9VZE4zeFhXUnpqb3ZMZlA1SE44OWM4dG4wZFFJREFRQUJBb0lCQUUzYkJOck5CeXVaWUxsUgpmMHhZN25OMThhY0FGdzJaWWpRQnIwa0Q5WWNOL3liWUN4dktUMDdkZUdZVnpOMWZFKzBldHd4OHQ2b1haNXZIClVXY0lvMDFwRDZxT0tOS1NQQ0dWYiszRFZjMVplcTlBZFNhNXplNmZRc3c0WWFzcFBjaU1jZHNrS3ZoRE9UOGsKYVA2bU1URDB1WWZuanVzdkJaNDh1VE9kRnpEZG15Z1AzYW94cFZYUmZFN2FvZWJjV2xLd21nTzI1bWZ4U3lxdwppS3FiclNPSlp1SnFjbks2cUovQzhNcFNhdktXQ3B5M3JCU0R3cjdkdGhSTDkxc2pHekxWeGtBMnNDMHhaLys3CmN1SWUvZnhzSWphc0hNRzJPOVJkbUd0RjQwbk9jNk40SzFxcDBnZ3FSUXg1VjBKaTBweGN5NkdCNXZJbXlNa1AKUlR1THdZRUNnWUVBeWZvQ0czUnpGOVRDWXgzUGxwak5aTkhsQkdtK0hpTjVZSGJUMUlIWXlvTVJDR2tvUXowdApXaEVQSyt6RE9NYVozRVBsWU9ZSm9UNU9MQmovVWhSbStsVnhQeHpscUxFYk04ZnJidUdaTnhzY0VKT2Rya2lGCkZRdUMxZTJDM1VPVnhnTm0wSGsxUDE1dWlnK0NoVWphaHdhbm16b0x0VVZxL1JQMytwSXh5bDBDZ1lFQXlRVFkKZ2YzTGQxQnNIZ2VNcGVmRlNieGRVOGlpa1JCVWhJckk0UTZnQkFZY05OTTVqUHprV3E0ZzY2ZEJRK2swaGNYaQpNV0RrRXhnNGdqc1F6Rlk3UjFiczltKzNMRW53VmowZjdidlZtVnl2RllHSlN5ay9YUU9Qek1wK3ZuaDFHK0NyCktTSDFZa3VNZEIyRkQ1SnNGNy9QUmlkQ1hlMWVUWXdFVng2YW9Qa0NnWUVBa0RUNG5ER2dtenRGTHc5eHo4eDUKbWFwaklhdCtHbmFwaXI1TXNFV2xTN0lZenpDRmxyeHZUUWN4RmVPTjMxT3ROeDhpL3ZRL20raW9WOFBoUi9GWgpOUk1jTUR1cG5iQVdBL3FSbGpGcyszTlhybDQzRHVDb1pFWTd2QkpBaFVwai9XVWdXMml2SS9lQVpRSjk1andHCkNySXRxUjdnalNSckp4YkN6eHppZitFQ2dZQU5jL2VSYTR6TVpXTjI5d1pnckF3MkRSY3Aza21TNzhiWVAvbUYKcGxickxnV0JPNG1rZCtCSWVWTFdzcERabktmWk5BOFpRdVRBcW1STnd1b3k0cXFBOGI1V0Y4L29kT0pTd3pCNQoxcEpLK3pyMGM0RGV1Tm4ydmFCSUVsMDlIZzZvV1BiYmY5eE9RY1FhbVVjb2JhSXlUTEh3ZmZ3aEVSdTRrT0JSCmZFalk4UUtCZ0FzYTFKcGl2VDFrYUMwbCtFK3g2VjdlVTFSaWhHM3lqd1lNVzdwNTJUaFBpb1F1TnRoYUtYcXMKZHRucm1ZM0kwNC84MUZaeWZqK0NmZ0V2Y1plRmFZK3lpNDRvWm5CU0dZWnZJc2hXQzRUQ1ZzL2hzUzlFelcwRwpTVExUdFpiWHRTaStOUCtEZ082VXdLVUNaOFlFMFptY3ZBOUtyU2sxM0dZTEhwWTFoZHZGCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==', 
                    clusterName: 'externalCluster', 
                    contextName: 'external',
                    credentialsId: 'user',
                    namespace: '',
                    serverUrl: 'https://90.84.243.143:5443') {

                        sh "kubectl get all"
 
                    }    
                }
        }

}
}